"""Add asset last_price

Revision ID: c2400e4781c9
Revises: 003
Create Date: 2025-12-06 17:07:08.725570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2400e4781c9'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('idx_position_snapshot_asset_date', table_name='position_snapshots')
    op.drop_index('idx_position_snapshot_portfolio', table_name='position_snapshots')
    op.drop_index('ix_position_snapshots_snapshot_date', table_name='position_snapshots')
    op.drop_table('position_snapshots')
    op.drop_index('idx_portfolio_snapshot_date', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshot_portfolio_date', table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_snapshot_date', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_positions_asset_id', table_name='positions')
    op.drop_index('ix_positions_id', table_name='positions')
    op.drop_index('ix_positions_portfolio_id', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_snapshot_metrics_portfolio_date', table_name='snapshot_metrics')
    op.drop_table('snapshot_metrics')
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_index('ix_usuarios_username', table_name='usuarios')
    op.drop_table('usuarios')
    op.alter_column('assets', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('assets', 'asset_type',
               existing_type=postgresql.ENUM('STOCK', 'CRYPTO', 'ETF', 'BOND', 'COMMODITY', 'CASH', name='assettype'),
               nullable=True)
    op.drop_index('ix_assets_id', table_name='assets')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.create_unique_constraint(None, 'assets', ['symbol'])
    op.drop_column('assets', 'currency')
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('portfolios', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('portfolios', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_portfolios_id', table_name='portfolios')
    op.drop_constraint('portfolios_user_id_fkey', 'portfolios', type_='foreignkey')
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.add_column('quotes', sa.Column('symbol', sa.String(length=20), nullable=False))
    op.add_column('quotes', sa.Column('date', sa.Date(), nullable=False))
    op.alter_column('quotes', 'open',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('quotes', 'high',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('quotes', 'low',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('quotes', 'close',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('quotes', 'volume',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('idx_quote_asset_timestamp', table_name='quotes')
    op.drop_index('idx_quote_timestamp', table_name='quotes')
    op.drop_index('ix_quotes_asset_id', table_name='quotes')
    op.drop_index('ix_quotes_timestamp', table_name='quotes')
    op.drop_constraint('uq_quote_asset_timestamp', 'quotes', type_='unique')
    op.create_index(op.f('ix_quotes_date'), 'quotes', ['date'], unique=False)
    op.create_index(op.f('ix_quotes_symbol'), 'quotes', ['symbol'], unique=False)
    op.drop_constraint('quotes_asset_id_fkey', 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'timestamp')
    op.drop_column('quotes', 'asset_id')
    op.add_column('results', sa.Column('total_buy_amount', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('results', sa.Column('total_current_amount', sa.Numeric(precision=18, scale=6), nullable=True))
    op.alter_column('results', 'portfolio_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('results', 'pnl_percent',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.drop_index('ix_results_id', table_name='results')
    op.drop_index('ix_results_portfolio_id', table_name='results')
    op.drop_column('results', 'total_invested')
    op.drop_column('results', 'updated_at')
    op.drop_column('results', 'total_current_value')
    op.alter_column('transactions', 'portfolio_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('transactions', 'asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('transactions', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=False)
    op.alter_column('transactions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('transactions', 'fees',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('transactions', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_transactions_asset_id', table_name='transactions')
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_index('ix_transactions_portfolio_id', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_portfolio_id', 'transactions', ['portfolio_id'], unique=False)
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.create_index('ix_transactions_asset_id', 'transactions', ['asset_id'], unique=False)
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('transactions', 'fees',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('transactions', 'price',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transactions', 'quantity',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transactions', 'asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('transactions', 'portfolio_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('results', sa.Column('total_current_value', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('total_invested', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True))
    op.create_index('ix_results_portfolio_id', 'results', ['portfolio_id'], unique=False)
    op.create_index('ix_results_id', 'results', ['id'], unique=False)
    op.alter_column('results', 'pnl_percent',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('results', 'portfolio_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('results', 'total_current_amount')
    op.drop_column('results', 'total_buy_amount')
    op.add_column('quotes', sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_foreign_key('quotes_asset_id_fkey', 'quotes', 'assets', ['asset_id'], ['id'])
    op.drop_index(op.f('ix_quotes_symbol'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_date'), table_name='quotes')
    op.create_unique_constraint('uq_quote_asset_timestamp', 'quotes', ['asset_id', 'timestamp'])
    op.create_index('ix_quotes_timestamp', 'quotes', ['timestamp'], unique=False)
    op.create_index('ix_quotes_asset_id', 'quotes', ['asset_id'], unique=False)
    op.create_index('idx_quote_timestamp', 'quotes', ['timestamp'], unique=False)
    op.create_index('idx_quote_asset_timestamp', 'quotes', ['asset_id', 'timestamp'], unique=False)
    op.alter_column('quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('quotes', 'volume',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quotes', 'close',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('quotes', 'low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('quotes', 'high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('quotes', 'open',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=False)
    op.drop_column('quotes', 'date')
    op.drop_column('quotes', 'symbol')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.create_foreign_key('portfolios_user_id_fkey', 'portfolios', 'usuarios', ['user_id'], ['id'])
    op.create_index('ix_portfolios_id', 'portfolios', ['id'], unique=False)
    op.alter_column('portfolios', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('portfolios', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('assets', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='unique')
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=True)
    op.create_index('ix_assets_id', 'assets', ['id'], unique=False)
    op.alter_column('assets', 'asset_type',
               existing_type=postgresql.ENUM('STOCK', 'CRYPTO', 'ETF', 'BOND', 'COMMODITY', 'CASH', name='assettype'),
               nullable=False)
    op.alter_column('assets', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_usuarios_username', 'usuarios', ['username'], unique=True)
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    op.create_table('snapshot_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('weekly_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('monthly_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('yearly_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('ytd_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('daily_volatility', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('weekly_volatility', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('sharpe_ratio', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('max_drawdown_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('best_day_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('best_day_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('worst_day_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('worst_day_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('asset_allocation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sector_allocation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='snapshot_metrics_portfolio_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='snapshot_metrics_pkey'),
    sa.UniqueConstraint('portfolio_id', 'metric_date', name='uq_portfolio_metrics_date')
    )
    op.create_index('idx_snapshot_metrics_portfolio_date', 'snapshot_metrics', ['portfolio_id', 'metric_date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('average_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='positions_asset_id_fkey'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='positions_portfolio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='positions_pkey'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='uq_portfolio_asset')
    )
    op.create_index('ix_positions_portfolio_id', 'positions', ['portfolio_id'], unique=False)
    op.create_index('ix_positions_id', 'positions', ['id'], unique=False)
    op.create_index('ix_positions_asset_id', 'positions', ['asset_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_invested', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('total_value', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('cash_balance', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('daily_pnl', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('daily_pnl_percent', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('total_pnl', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('total_pnl_percent', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('number_of_positions', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=False),
    sa.Column('number_of_assets', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('calculation_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='portfolio_snapshots_portfolio_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='portfolio_snapshots_pkey'),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_portfolio_snapshot_date'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_portfolio_snapshots_snapshot_date', 'portfolio_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_portfolio_snapshot_portfolio_date', 'portfolio_snapshots', ['portfolio_id', 'snapshot_date'], unique=False)
    op.create_index('idx_portfolio_snapshot_date', 'portfolio_snapshots', ['snapshot_date'], unique=False)
    op.create_table('position_snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('portfolio_snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=24, scale=8), autoincrement=False, nullable=False),
    sa.Column('average_buy_price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('position_pnl', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('position_pnl_percent', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('daily_change', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('daily_change_percent', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('portfolio_weight', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='position_snapshots_asset_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_snapshot_id'], ['portfolio_snapshots.id'], name='position_snapshots_portfolio_snapshot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='position_snapshots_pkey')
    )
    op.create_index('ix_position_snapshots_snapshot_date', 'position_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_position_snapshot_portfolio', 'position_snapshots', ['portfolio_snapshot_id'], unique=False)
    op.create_index('idx_position_snapshot_asset_date', 'position_snapshots', ['asset_id', 'snapshot_date'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
